<?php

namespace GomdimApps\LaravelMCPPilot\Search\Persistence\Models;

use GomdimApps\LaravelMCPPilot\Search\Persistence\SearchConnection;
use Illuminate\Database\Eloquent\Model;

class Entry extends Model
{
    protected $table = 'search_entries';

    protected $connection = SearchConnection::NAME;

    public $timestamps = false;

    // Ids are assigned explicitly by SearchIndexRepository (see the create_search_entries_table
    // migration), not generated by SQLite.
    public $incrementing = false;

    protected $keyType = 'int';

    protected $guarded = [];

    protected $casts = [
        'payload' => 'array',
    ];
}
